#========================================= Swagger configuration =====================================#
swagger:
  title: HavenPay API documentation
  desc: HavenPay API documentation
  version: 1.0.0
  tag: ""
  apiPath: /api/docs


