#========================================= Swagger configuration =====================================#
swagger:
  title: HavenPay API documentation
  desc: HavenPay API documentation
  version: 1.0.0
  tag: ""
  apiPath: /api/docs


#========================================= Omnix configuration =======================================#
omnix:
  connection:
    channel: test
    access-token-expiration-in-min: 30
  api:
    baseurl: http://apiv2.accionmfb.com:2002/omnix/api
    parameters: /generate/{channel}/parameters
    credentials: /generate/{channel}/credentials
    otp: /profileService/customer/otp/push
    create-customer: /profileService/customer/individual
